# Generated by Django 3.0.6 on 2020-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
